# Generated by Django 3.2.4 on 2021-08-16 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
