# Generated by Django 3.2.4 on 2021-08-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210803_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='google_plus',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
